### PR TITLE
Update actions/checkout and actions/setup-go to v3

### PR DESCRIPTION
**Pull request by raukadah**
It will fix the github actions Annotations warning coming here: https://github.com/openstack-k8s-operators/ansibleee-operator/actions/runs/3647655700

Signed-off-by: Chandan Kumar (raukadah) <raukadah@gmail.com>

### CODE REVIEW

**Comment by Sandeepyadav93** [comment]
This Pr looks good to me, A note about our workflow - currently, we are duplicating these workflows in each repo, probably best if we use reusable workflow so that we don't have to update workflow on each repo.

**Comment by Sandeepyadav93** [comment]
@raukadah found two more occurences of v2, do you want to update these as well?

https://github.com/openstack-k8s-operators/ansibleee-operator/blob/4296428890fca2697b1b88916cd6fae76ebe9c13/.github/workflows/build-ansibleee-operator.yaml#L87-L88

https://github.com/openstack-k8s-operators/ansibleee-operator/blob/4296428890fca2697b1b88916cd6fae76ebe9c13/.github/workflows/build-ansibleee-operator.yaml#L155-L156

**Review by jlarriba — APPROVED** [review]
/lgtm

**Pull request merged**
