### PR TITLE
Revert "Bump k8s.io/api from 0.25.4 to 0.26.0"

### PR DESCRIPTION
**Pull request by SeanMooney**
Reverts openstack-k8s-operators/ansibleee-operator#35
due to issue https://github.com/openstack-k8s-operators/ansibleee-operator/issues/45
based on discussion in https://app.slack.com/client/T027F3GAJ/CQXJFGMK6/thread/CQXJFGMK6-1673492040.792329

### CODE REVIEW

**Review by fao89 — APPROVED** [review]

**Review by fultonj — APPROVED** [review]

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
